import "./globals.css";
import Navbar from "./components/Navbar";
import Provider from "./SessionProvider";

export const metadata = {
  title: "Anonymous Post",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <html lang="en">
        <body>
          <div className="min-h-screen h-screen w-full ">
            <div className="container mx-auto ">
              <Navbar />
              {children}
            </div>
          </div>
        </body>
      </html>
    </Provider>
  );
}
